/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.h
**     Project     : S32K_BSP
**     Processor   : S32K144_100
**     Component   : S32K144_100
**     Version     : Component 01.197, Driver 01.00, CPU db: 3.00.000
**     Datasheet   : S32K14XRM Rev. 2, 02/2017
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-11, 13:43, # CodeGen: 25
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**         SystemSoftwareReset   - void SystemSoftwareReset(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file Cpu.h
** @version 01.00
** @brief
**
*/
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/

#ifndef Cpu_H
#define Cpu_H

/* MODULE Cpu. */

/*Include shared modules, which are used for whole project*/
#include "device_registers.h"
#include "clock_manager.h"
#include "interrupt_manager.h"
#include "adc_driver.h"
#include "edma_driver.h"
#include "flexcan_driver.h"
#include "ftm_ic_driver.h"
#include "ftm_oc_driver.h"
#include "ftm_mc_driver.h"
#include "ftm_qd_driver.h"
#include "ftm_pwm_driver.h"
#include "lpuart_driver.h"
#include "lpit_driver.h"
#include "flash_driver.h"
#include "lpspi_master_driver.h"
#include "lpspi_slave_driver.h"
#include "lpspi_shared_function.h"
#include "lpi2c_driver.h"
#include "lptmr_driver.h"
#include "wdog_driver.h"
#include "rtc_driver.h"
#include "pdb_driver.h"
#include "crc_driver.h"
#include "device_registers.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TBD Cpu configuration will be declared here. */




#ifdef __cplusplus
}
#endif

/* END Cpu. */

#endif
/* Cpu_H */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
