/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : lpspiCom1.h
**     Project     : S32K_BSP
**     Processor   : S32K144_100
**     Component   : lpspi
**     Version     : Component 1.0.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_07
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-11, 13:43, # CodeGen: 25
**     Contents    :
**         LPSPI_DRV_MasterInit              - status_t LPSPI_DRV_MasterInit(uint32_t instance,lpspi_state_t *...
**         LPSPI_DRV_MasterDeinit            - status_t LPSPI_DRV_MasterDeinit(uint32_t instance);
**         LPSPI_DRV_MasterSetDelay          - status_t LPSPI_DRV_MasterSetDelay(uint32_t instance,uint32_t...
**         LPSPI_DRV_MasterConfigureBus      - status_t LPSPI_DRV_MasterConfigureBus(uint32_t instance,const...
**         LPSPI_DRV_MasterTransferBlocking  - status_t LPSPI_DRV_MasterTransferBlocking(uint32_t instance,const uint8_t *...
**         LPSPI_DRV_MasterTransfer          - status_t LPSPI_DRV_MasterTransfer(uint32_t instance,const uint8_t *...
**         LPSPI_DRV_MasterGetTransferStatus - status_t LPSPI_DRV_MasterGetTransferStatus(uint32_t instance,uint32_t *...
**         LPSPI_DRV_MasterAbortTransfer     - status_t LPSPI_DRV_MasterAbortTransfer(uint32_t instance);
**         LPSPI_DRV_SlaveInit               - status_t LPSPI_DRV_SlaveInit(uint32_t instance,lpspi_state_t *...
**         LPSPI_DRV_SlaveDeinit             - status_t LPSPI_DRV_SlaveDeinit(uint32_t instance);
**         LPSPI_DRV_SlaveTransferBlocking   - status_t LPSPI_DRV_SlaveTransferBlocking(uint32_t instance,const uint8_t *...
**         LPSPI_DRV_SlaveTransfer           - status_t LPSPI_DRV_SlaveTransfer(uint32_t instance,const uint8_t *...
**         LPSPI_DRV_SlaveAbortTransfer      - status_t LPSPI_DRV_SlaveAbortTransfer(uint32_t instance);
**         LPSPI_DRV_SlaveGetTransferStatus  - status_t LPSPI_DRV_SlaveGetTransferStatus(uint32_t instance,uint32_t *...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file lpspiCom1.h
** @version 01.00
*/
/*!
**  @addtogroup lpspiCom1_module lpspiCom1 module documentation
**  @{
*/
#ifndef lpspiCom1_H
#define lpspiCom1_H
/* MODULE lpspiCom1. */

/* MODULE lpspiCom1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
//#include "dmaController1.h"
#include "osif1.h"

/*! @brief Number of CAN instances */
#define NUMBER_OF_SPI_INSTANCES (2U)

/*! @brief Device instance number for Master */
#define LPSPICOM0 (0U)
/*! @brief Device instance number for Slave */
#define LPSPICOM1 (1U)

/*! @brief Driver and configuration structure
 * Implements : struct_spi_config
 */
typedef struct
{
    uint8_t spi_instance_number;
    lpspi_state_t spi_state_struct;
    const lpspi_master_config_t * const spi_init_master_config_struct;
    const lpspi_slave_config_t * const spi_init_slave_config_struct;
} struct_spi_config_t;

/*! @brief Declaration of the driver and configuration table structure */
extern struct_spi_config_t struct_spi_config_tbl[NUMBER_OF_SPI_INSTANCES];

#endif

