/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pdb1.h
**     Project     : S32K_BSP
**     Processor   : S32K144_100
**     Component   : pdb
**     Version     : Component SDK_S32K14x_07, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_07
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-01-11, 13:43, # CodeGen: 25
**     Contents    :
**         PDB_DRV_Init                          - void PDB_DRV_Init(const uint32_t instance, const pdb_timer_config_t *...
**         PDB_DRV_Deinit                        - void PDB_DRV_Deinit(const uint32_t instance);
**         PDB_DRV_SoftTriggerCmd                - void PDB_DRV_SoftTriggerCmd(const uint32_t instance);
**         PDB_DRV_GetTimerValue                 - uint32_t PDB_DRV_GetTimerValue(const uint32_t instance);
**         PDB_DRV_GetTimerIntFlag               - bool PDB_DRV_GetTimerIntFlag(const uint32_t instance);
**         PDB_DRV_ClearTimerIntFlag             - void PDB_DRV_ClearTimerIntFlag(const uint32_t instance);
**         PDB_DRV_LoadValuesCmd                 - void PDB_DRV_LoadValuesCmd(const uint32_t instance);
**         PDB_DRV_SetTimerModulusValue          - void PDB_DRV_SetTimerModulusValue(const uint32_t instance, const uint32_t...
**         PDB_DRV_SetValueForTimerInterrupt     - void PDB_DRV_SetValueForTimerInterrupt(const uint32_t instance, const...
**         PDB_DRV_ConfigAdcPreTrigger           - void PDB_DRV_ConfigAdcPreTrigger(const uint32_t instance, const uint32_t chn,...
**         PDB_DRV_GetAdcPreTriggerFlags         - uint32_t PDB_DRV_GetAdcPreTriggerFlags(const uint32_t instance, const...
**         PDB_DRV_ClearAdcPreTriggerFlags       - void PDB_DRV_ClearAdcPreTriggerFlags(const uint32_t instance, const uint32_t...
**         PDB_DRV_GetAdcPreTriggerSeqErrFlags   - uint32_t PDB_DRV_GetAdcPreTriggerSeqErrFlags(const uint32_t instance, const...
**         PDB_DRV_ClearAdcPreTriggerSeqErrFlags - void PDB_DRV_ClearAdcPreTriggerSeqErrFlags(const uint32_t instance, const...
**         PDB_DRV_SetAdcPreTriggerDelayValue    - void PDB_DRV_SetAdcPreTriggerDelayValue(const uint32_t instance, const...
**         PDB_DRV_SetCmpPulseOutEnable          - void PDB_DRV_SetCmpPulseOutEnable(const uint32_t instance, const uint32_t...
**         PDB_DRV_SetCmpPulseOutDelayForHigh    - void PDB_DRV_SetCmpPulseOutDelayForHigh(const uint32_t instance, const...
**         PDB_DRV_SetCmpPulseOutDelayForLow     - void PDB_DRV_SetCmpPulseOutDelayForLow(const uint32_t instance, const...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file pdb1.h
** @version 01.00
*/
/*!
**  @addtogroup pdb1_module pdb1 module documentation
**  @{
*/
#ifndef pdb1_H
#define pdb1_H
/* MODULE pdb1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 */

/* Include inherited beans */
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_PDB1 (0UL)
#define INST_PDB2 (1UL)


typedef struct
{
	uint32_t instance;
	uint32_t chn;
    pdb_adc_pretrigger_config_t adc_trigger_init_config;
}struct_PDB_CONFIG_t;


/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig0;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig1;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig2;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig3;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig4;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig5;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig6;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig7;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig8;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig9;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig10;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig11;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig12;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig13;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig14;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig15;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig16;
/*! @brief ADC pre-trigger configuration declaration */

extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig19;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig20;

/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig21;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig25;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig26;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig27;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig28;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig29;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb1_AdcTrigInitConfig30;


/*! @brief PDB timer init config declaration */
extern const pdb_timer_config_t pdb_InitConfig0;


/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig0;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig1;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig2;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig3;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig4;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig5;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig6;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig7;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig8;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig9;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig10;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig11;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig12;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig13;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig14;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig15;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig18;
/*! @brief ADC pre-trigger configuration declaration */
extern const pdb_adc_pretrigger_config_t pdb2_AdcTrigInitConfig23;

extern const struct_PDB_CONFIG_t pdb_config_tbl[];

uint16_t get_element_count_pdb_config_tbl(void);

void pdb0_init(void);
void pdb1_init(void);

#endif
/* ifndef pdb1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
