
/* MODULE io_tables. */
#include "io_tables.h"
#include "adConv1.h"

#include "flexTimer1.h"





#include "device_registers.h"

/*! @brief Array of pin configuration structures */
pin_settings_config_t g_pin_mux_InitConfigArr[NUM_OF_CONFIGURED_PINS] = {

//            - PORTA -             ,  - PORTA -                ,  - PORTA -                                            ,  - PORTA -                      ,  - PORTA -                                      ,  - PORTA -                        ,  - PORTA -                ,  - PORTA -                                  ,  - PORTA -                     ,  - PORTA -               ,  - PORTA -                    ,               - PORTA -                                
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                  , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                               
{            .base = PORTA          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_NONE          , },           // DI_AI_MOTOR_1_VM1                      
{            .base = PORTA          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DOX_SHIFT_OE_N                         
{            .base = PORTA          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // MC_I2C_SDA                             
{            .base = PORTA          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // MC_I2C_SCL                             
{            .base = PORTA          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_NONE          , },           // DI_AIX_MUX_1                           
{            .base = PORTA          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_NONE          , },           // DI_AIX_MUX_2                           
{            .base = PORTA          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_LIN_EN                              
{            .base = PORTA          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_MOTOR_2_INH                         
{            .base = PORTA          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // CAN_EN1                                
{            .base = PORTA          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // MC_FREQ_IN4                            
{            .base = PORTA          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_IN            , },           // MC_FREQ_IN3                            
{            .base = PORTA          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // CAN_WAKE1                              
{            .base = PORTA          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_NONE          , },           // DI_AIX_MUX_3                           
{            .base = PORTA          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_NONE          , },           // DI_AIX_MUX_4                           
{            .base = PORTA          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_MOTOR_1_INH                         
{            .base = PORTA          , .pinPortIdx = 25          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT13                       
{            .base = PORTA          , .pinPortIdx = 26          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT14                       
{            .base = PORTA          , .pinPortIdx = 27          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT15                       
{            .base = PORTA          , .pinPortIdx = 28          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT16                       
{            .base = PORTA          , .pinPortIdx = 29          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_MOTOR_1_INH_2                       
{            .base = PORTA          , .pinPortIdx = 30          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DOX_SHIFT_DS_INTERFACE                 
{            .base = PORTA          , .pinPortIdx = 31          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTA          , .direction = PD_OUT           , },           // DO_MOTOR_2_INH_2                       
//            - PORTB -             ,  - PORTB -                ,  - PORTB -                                            ,  - PORTB -                      ,  - PORTB -                                      ,  - PORTB -                        ,  - PORTB -                ,  - PORTB -                                  ,  - PORTB -                     ,  - PORTB -               ,  - PORTB -                    ,               - PORTB -                                
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                  , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                               
{            .base = PORTB          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_SCI_RXD                             
{            .base = PORTB          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // MC_SCI_TXD                             
{            .base = PORTB          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_FREQ_IN2                            
{            .base = PORTB          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_FREQ_IN1                            
{            .base = PORTB          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_10                      
{            .base = PORTB          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_11                      
{            .base = PORTB          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // XTAL                                   
{            .base = PORTB          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = 0            , .direction = PD_NONE          , },           // EXTAL                                  
{            .base = PORTB          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DOX_SHIFT_ST_CP                        
{            .base = PORTB          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_DEBUG_LED                       
{            .base = PORTB          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_2                       
{            .base = PORTB          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_7                       
{            .base = PORTB          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT4              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_IN            , },           // MC_CAN_RXD3                            
{            .base = PORTB          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT4              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // MC_CAN_TXD3                            
{            .base = PORTB          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_VREF                             
{            .base = PORTB          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_X1000_19_RS485_RS232_AE          
{            .base = PORTB          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_PIGGY_1                          
{            .base = PORTB          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_CS_DIS                              
{            .base = PORTB          , .pinPortIdx = 18          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_9                       
{            .base = PORTB          , .pinPortIdx = 20          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_HSD_CURRENT_OUT_13               
{            .base = PORTB          , .pinPortIdx = 21          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_HSD_CURRENT_OUT_14               
{            .base = PORTB          , .pinPortIdx = 22          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_HSD_CURRENT_OUT_15               
{            .base = PORTB          , .pinPortIdx = 23          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DO_PWM_SOLAR_LOAD                      
{            .base = PORTB          , .pinPortIdx = 25          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DOX_SHIFT_SH_CP                        
{            .base = PORTB          , .pinPortIdx = 27          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DOX_SHIFT_IN_DS                        
{            .base = PORTB          , .pinPortIdx = 28          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_NONE          , },           // DI_AI_KL30                             
{            .base = PORTB          , .pinPortIdx = 29          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTB          , .direction = PD_OUT           , },           // DOX_SHIFT_MR_N                         
//            - PORTC -             ,  - PORTC -                ,  - PORTC -                                            ,  - PORTC -                      ,  - PORTC -                                      ,  - PORTC -                        ,  - PORTC -                ,  - PORTC -                                  ,  - PORTC -                     ,  - PORTC -               ,  - PORTC -                    ,               - PORTC -                                
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                  , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                               
{            .base = PORTC          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_8                       
{            .base = PORTC          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_PIGGY_2                          
{            .base = PORTC          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_PIGGY_3                          
{            .base = PORTC          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_PIGGY_4                          
{            .base = PORTC          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_IN            , },           // MC_CAN_RXD2                            
{            .base = PORTC          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // MC_CAN_TXD2                            
{            .base = PORTC          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_NMEA_2000_MESSUNG                   
{            .base = PORTC          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_6                       
{            .base = PORTC          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_4                       
{            .base = PORTC          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_LIN_WAKE                            
{            .base = PORTC          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_5                       
{            .base = PORTC          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_1                      
{            .base = PORTC          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_2                      
{            .base = PORTC          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_3                      
{            .base = PORTC          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_4                      
{            .base = PORTC          , .pinPortIdx = 19          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_5                      
{            .base = PORTC          , .pinPortIdx = 23          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_6                      
{            .base = PORTC          , .pinPortIdx = 27          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_7                      
{            .base = PORTC          , .pinPortIdx = 28          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_3                       
{            .base = PORTC          , .pinPortIdx = 29          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_8                      
{            .base = PORTC          , .pinPortIdx = 30          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_HSD_CURRENT_OUT_16               
{            .base = PORTC          , .pinPortIdx = 31          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTC          , .direction = PD_NONE          , },           // DI_AI_SOLAR_I                          
//            - PORTD -             ,  - PORTD -                ,  - PORTD -                                            ,  - PORTD -                      ,  - PORTD -                                      ,  - PORTD -                        ,  - PORTD -                ,  - PORTD -                                  ,  - PORTD -                     ,  - PORTD -               ,  - PORTD -                    ,               - PORTD -                                
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                  , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                               
{            .base = PORTD          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // MC_SPI_CLK_PIGGY                       
{            .base = PORTD          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // MC_SPI_MISO_PIGGY                      
{            .base = PORTD          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT3              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // MC_SPI_MOSI_PIGGY                      
{            .base = PORTD          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_SPI_CS_PIGGY                        
{            .base = PORTD          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_TASTER_2                         
{            .base = PORTD          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DOX_SHIFT_SH_CP_INTERFACE              
{            .base = PORTD          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_MUX_A_ANA                           
{            .base = PORTD          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_MUX_B_ANA                           
{            .base = PORTD          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_MUX_C_ANA                           
{            .base = PORTD          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT6              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // MC_FREQ_KL15                           
{            .base = PORTD          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // MC_FREQ_IN6                            
{            .base = PORTD          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_IN            , },           // MC_FREQ_IN5                            
{            .base = PORTD          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DOX_SHIFT_OE_INTERFACE_N               
{            .base = PORTD          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_RS_DCDC_10V                         
{            .base = PORTD          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_KL30_EN                             
{            .base = PORTD          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_POWER_EN                            
{            .base = PORTD          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DOX_SHIFT_MR_INTERFACE_N               
{            .base = PORTD          , .pinPortIdx = 17          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_VREF_EN                             
{            .base = PORTD          , .pinPortIdx = 18          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_TASTER                           
{            .base = PORTD          , .pinPortIdx = 19          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_9                      
{            .base = PORTD          , .pinPortIdx = 22          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_10                     
{            .base = PORTD          , .pinPortIdx = 23          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_11                     
{            .base = PORTD          , .pinPortIdx = 24          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_NONE          , },           // DI_AI_HSD_SENSE_12                     
{            .base = PORTD          , .pinPortIdx = 27          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_PWM_MOTOR_1_POS                     
{            .base = PORTD          , .pinPortIdx = 28          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_PWM_MOTOR_1_NEG                     
{            .base = PORTD          , .pinPortIdx = 29          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_PWM_MOTOR_2_POS                     
{            .base = PORTD          , .pinPortIdx = 30          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTD          , .direction = PD_OUT           , },           // DO_PWM_MOTOR_2_NEG                     
//            - PORTE -             ,  - PORTE -                ,  - PORTE -                                            ,  - PORTE -                      ,  - PORTE -                                      ,  - PORTE -                        ,  - PORTE -                ,  - PORTE -                                  ,  - PORTE -                     ,  - PORTE -               ,  - PORTE -                    ,               - PORTE -                                
             // .base               , // pinPortIndex           , // pullConfig                                         , // passiveFilter                , // driveSelect                                  , // mux                            , // pinLock                , // intConfig                                , // clearIntFlag                , // gpioBase              , // direction                  ,              // pin name                               
{            .base = PORTE          , .pinPortIdx = 0           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // CAN_ERR1                               
{            .base = PORTE          , .pinPortIdx = 1           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_STB1                               
{            .base = PORTE          , .pinPortIdx = 2           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_1_VM                       
{            .base = PORTE          , .pinPortIdx = 3           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_STB2                               
{            .base = PORTE          , .pinPortIdx = 4           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT5              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // MC_CAN_RXD1                            
{            .base = PORTE          , .pinPortIdx = 5           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT5              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // MC_CAN_TXD1                            
{            .base = PORTE          , .pinPortIdx = 6           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_2_VM1                      
{            .base = PORTE          , .pinPortIdx = 7           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_EN3                                
{            .base = PORTE          , .pinPortIdx = 8           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_12                      
{            .base = PORTE          , .pinPortIdx = 9           , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_STB3                               
{            .base = PORTE          , .pinPortIdx = 10          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // CAN_ERR3                               
{            .base = PORTE          , .pinPortIdx = 11          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_WAKE3                              
{            .base = PORTE          , .pinPortIdx = 12          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_EN2                                
{            .base = PORTE          , .pinPortIdx = 13          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // CAN_ERR2                               
{            .base = PORTE          , .pinPortIdx = 14          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // CAN_WAKE2                              
{            .base = PORTE          , .pinPortIdx = 15          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT4              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_IN            , },           // MC_FREQ_IN7                            
{            .base = PORTE          , .pinPortIdx = 16          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_AS_GPIO           , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DOX_SHIFT_ST_CP_INTERFACE              
{            .base = PORTE          , .pinPortIdx = 19          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_SOLAR_V                          
{            .base = PORTE          , .pinPortIdx = 20          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_MUX_ALT2              , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_OUT           , },           // DO_PWM_HSD_OUT_1                       
{            .base = PORTE          , .pinPortIdx = 21          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_2_VM                       
{            .base = PORTE          , .pinPortIdx = 22          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_2_IS_NEG                   
{            .base = PORTE          , .pinPortIdx = 23          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_1_IS_NEG                   
{            .base = PORTE          , .pinPortIdx = 24          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_2_IS_POSITIVE              
{            .base = PORTE          , .pinPortIdx = 25          , .pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED          , .passiveFilter = false          , .driveSelect = PORT_LOW_DRIVE_STRENGTH          , .mux = PORT_PIN_DISABLED          , .pinLock = false          , .intConfig = PORT_DMA_INT_DISABLED          , .clearIntFlag = false          , .gpioBase = PTE          , .direction = PD_NONE          , },           // DI_AI_MOTOR_1_IS_POSITIVE              
  
};

/* Virtual Pins configuration structure */
struct_VIRTUAL_PINS_CFG virtual_pin[VIRTUAL_PIN_MAX - PIN_MAX] = {
{ .name = DOM_BEREICH_30V_7                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_6                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_5                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_4                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_3                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_2                 , .current_val = 0           },
{ .name = DOM_BEREICH_30V_1                 , .current_val = 0           },
{ .name = DOM_PD7                           , .current_val = 0           },
{ .name = DOM_PD6                           , .current_val = 0           },
{ .name = DOM_PD5                           , .current_val = 0           },
{ .name = DOM_PD4                           , .current_val = 0           },
{ .name = DOM_PD3                           , .current_val = 0           },
{ .name = DOM_PD2                           , .current_val = 0           },
{ .name = DOM_PD1                           , .current_val = 0           },
{ .name = DOM_PU7                           , .current_val = 0           },
{ .name = DOM_PU6                           , .current_val = 0           },
{ .name = DOM_PU5                           , .current_val = 0           },
{ .name = DOM_PU4                           , .current_val = 0           },
{ .name = DOM_PU3                           , .current_val = 0           },
{ .name = DOM_PU2                           , .current_val = 0           },
{ .name = DOM_PU1                           , .current_val = 0           },
{ .name = DIM_IN1                           , .current_val = 0           },
{ .name = DIM_IN2                           , .current_val = 0           },
{ .name = DIM_IN3                           , .current_val = 0           },
{ .name = DIM_IN4                           , .current_val = 0           },
{ .name = DIM_IN5                           , .current_val = 0           },
{ .name = DIM_IN6                           , .current_val = 0           },
{ .name = DIM_IN7                           , .current_val = 0           },
{ .name = DIM_KL_15                         , .current_val = 0           },
{ .name = DIM_VDD_NMEA                      , .current_val = 0           },
{ .name = DIM_PIGGY_VARIANTE_LEFT           , .current_val = 0           },
{ .name = DIM_PIGGY_VARIANTE_RIGHT          , .current_val = 0           },
{ .name = DIM_HSD_IO_1                      , .current_val = 0           },
{ .name = DIM_HSD_IO_2                      , .current_val = 0           },
{ .name = DIM_HSD_IO_3                      , .current_val = 0           },
{ .name = DIM_HSD_IO_4                      , .current_val = 0           },
{ .name = DIM_HSD_IO_5                      , .current_val = 0           },
{ .name = DIM_HSD_IO_6                      , .current_val = 0           },
{ .name = DIM_HSD_IO_7                      , .current_val = 0           },
{ .name = DIM_HSD_IO_8                      , .current_val = 0           },
{ .name = DIM_HSD_IO_9                      , .current_val = 0           },
{ .name = DIM_HSD_IO_10                     , .current_val = 0           },
{ .name = DIM_HSD_IO_11                     , .current_val = 0           },
{ .name = DIM_HSD_IO_12                     , .current_val = 0           },
{ .name = DIM_HSD_IO_13                     , .current_val = 0           },
{ .name = DIM_HSD_IO_14                     , .current_val = 0           },
{ .name = DIM_HSD_IO_15                     , .current_val = 0           },
{ .name = DIM_HSD_IO_16                     , .current_val = 0           },
  
};


/* ADC configuration structure */
const struct_adc_config_t adc_config_tbl[ADC_MAX + 1] = {
            // name                                     , // adc_instance                       , // adc_channel              , // adc_vref high            , // resolution               , // multiplex                , // multiplex group             , // cal_index              , // calibration type                               
{           .name = AI_MOTOR_1_VM1                      , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIX_MUX_1                           , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIX_MUX_2                           , .adc_instance = INST_ADCONV1          , .adc_channel = 2u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_PIGGY_2                          , .adc_instance = INST_ADCONV1          , .adc_channel = 8u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_PIGGY_3                          , .adc_instance = INST_ADCONV1          , .adc_channel = 9u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_PIGGY_4                          , .adc_instance = INST_ADCONV1          , .adc_channel = 10u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_HSD_SENSE_1                      , .adc_instance = INST_ADCONV1          , .adc_channel = 11u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_2                      , .adc_instance = INST_ADCONV1          , .adc_channel = 12u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 12           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_3                      , .adc_instance = INST_ADCONV1          , .adc_channel = 13u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 24           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_4                      , .adc_instance = INST_ADCONV1          , .adc_channel = 14u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 36           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_CURRENT_OUT_13               , .adc_instance = INST_ADCONV1          , .adc_channel = 16u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_HSD_CURRENT_OUT_14               , .adc_instance = INST_ADCONV1          , .adc_channel = 17u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_HSD_CURRENT_OUT_15               , .adc_instance = INST_ADCONV1          , .adc_channel = 18u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_KL30                             , .adc_instance = INST_ADCONV1          , .adc_channel = 19u          , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_HSD_SENSE_5                      , .adc_instance = INST_ADCONV1          , .adc_channel = 24u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 48           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_6                      , .adc_instance = INST_ADCONV1          , .adc_channel = 25u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 60           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_7                      , .adc_instance = INST_ADCONV1          , .adc_channel = 26u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 72           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_8                      , .adc_instance = INST_ADCONV1          , .adc_channel = 27u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 84           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_CURRENT_OUT_16               , .adc_instance = INST_ADCONV1          , .adc_channel = 28u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_SOLAR_I                          , .adc_instance = INST_ADCONV1          , .adc_channel = 29u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_TASTER_2                         , .adc_instance = INST_ADCONV2          , .adc_channel = 0u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_VREF                             , .adc_instance = INST_ADCONV2          , .adc_channel = 1u           , .adc_vrefh = 14444          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_MOTOR_1_VM                       , .adc_instance = INST_ADCONV2          , .adc_channel = 2u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIX_MUX_3                           , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIX_MUX_4                           , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_X1000_19_RS485_RS232_AE          , .adc_instance = INST_ADCONV2          , .adc_channel = 5u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_MOTOR_2_VM1                      , .adc_instance = INST_ADCONV2          , .adc_channel = 6u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_PIGGY_1                          , .adc_instance = INST_ADCONV2          , .adc_channel = 8u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_TASTER                           , .adc_instance = INST_ADCONV2          , .adc_channel = 9u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_HSD_SENSE_9                      , .adc_instance = INST_ADCONV2          , .adc_channel = 10u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 96           , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_10                     , .adc_instance = INST_ADCONV2          , .adc_channel = 11u          , .adc_vrefh = 15152          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 108          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_11                     , .adc_instance = INST_ADCONV2          , .adc_channel = 12u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 120          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_HSD_SENSE_12                     , .adc_instance = INST_ADCONV2          , .adc_channel = 13u          , .adc_vrefh = 23333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 132          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_SOLAR_V                          , .adc_instance = INST_ADCONV2          , .adc_channel = 14u          , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_MOTOR_2_VM                       , .adc_instance = INST_ADCONV2          , .adc_channel = 15u          , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AI_MOTOR_2_IS_NEG                   , .adc_instance = INST_ADCONV2          , .adc_channel = 16u          , .adc_vrefh = 33333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 144          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_MOTOR_1_IS_NEG                   , .adc_instance = INST_ADCONV2          , .adc_channel = 17u          , .adc_vrefh = 33333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 156          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_MOTOR_2_IS_POSITIVE              , .adc_instance = INST_ADCONV2          , .adc_channel = 18u          , .adc_vrefh = 33333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 168          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AI_MOTOR_1_IS_POSITIVE              , .adc_instance = INST_ADCONV2          , .adc_channel = 19u          , .adc_vrefh = 33333          , .resolution = 4096          , .multiplex = FALSE          , .multiplex_group  = 0          , .cal_index = 180          , .cal_type = CALIB_SOURCE_3P           },          
{           .name = AIM_IN_1                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_2                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_3                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 2          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_4                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 3          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_5                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 4          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_6                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 5          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_IN_7                            , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 16920          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 6          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_POWER_TEMP                      , .adc_instance = INST_ADCONV1          , .adc_channel = 0u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 7          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_TEMP_1                          , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_TEMP_3                          , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_TEMP_2                          , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 2          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_TEMP_OUT_13_16                  , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 3          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_KL_15                           , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 4          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_VDD_NMEA                        , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 5          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_PIGGY_VARIANTE_LEFT             , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 6          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_PIGGY_VARIANTE_RIGHT            , .adc_instance = INST_ADCONV1          , .adc_channel = 1u           , .adc_vrefh = 5000           , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 7          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_1                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_2                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_3                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 2          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_4                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 3          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_5                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 4          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_6                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 5          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_7                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 6          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_8                        , .adc_instance = INST_ADCONV2          , .adc_channel = 3u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 7          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_9                        , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 0          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_10                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 1          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_11                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 2          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_12                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 3          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_13                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 4          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_14                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 5          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_15                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 6          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
{           .name = AIM_HSD_IO_16                       , .adc_instance = INST_ADCONV2          , .adc_channel = 4u           , .adc_vrefh = 33000          , .resolution = 4096          , .multiplex = TRUE           , .multiplex_group  = 7          , .cal_index = 0            , .cal_type = CALIB_NONE                },          
 
};

/* PWM config table */
struct_FTM_CONFIG struct_ftm_config_tbl[FREQ_MAX + 1] =
{
            // Pin Name                          , // PWM instance of the pin           , // PWM channel                          
{           .pin_name = PWM_DEBUG_LED            , .pwm_instance = MODULE_3             , .pwm_channel = 1            },          
{           .pin_name = PWM_HSD_OUT_1            , .pwm_instance = MODULE_4             , .pwm_channel = 0            },          
{           .pin_name = PWM_HSD_OUT_2            , .pwm_instance = MODULE_3             , .pwm_channel = 2            },          
{           .pin_name = PWM_HSD_OUT_3            , .pwm_instance = MODULE_4             , .pwm_channel = 7            },          
{           .pin_name = PWM_HSD_OUT_4            , .pwm_instance = MODULE_3             , .pwm_channel = 5            },          
{           .pin_name = PWM_HSD_OUT_5            , .pwm_instance = MODULE_3             , .pwm_channel = 7            },          
{           .pin_name = PWM_HSD_OUT_6            , .pwm_instance = MODULE_3             , .pwm_channel = 4            },          
{           .pin_name = PWM_HSD_OUT_7            , .pwm_instance = MODULE_3             , .pwm_channel = 3            },          
{           .pin_name = PWM_HSD_OUT_8            , .pwm_instance = MODULE_0             , .pwm_channel = 0            },          
{           .pin_name = PWM_HSD_OUT_9            , .pwm_instance = MODULE_5             , .pwm_channel = 7            },          
{           .pin_name = PWM_HSD_OUT_10           , .pwm_instance = MODULE_0             , .pwm_channel = 4            },          
{           .pin_name = PWM_HSD_OUT_11           , .pwm_instance = MODULE_0             , .pwm_channel = 5            },          
{           .pin_name = PWM_HSD_OUT_12           , .pwm_instance = MODULE_0             , .pwm_channel = 6            },          
{           .pin_name = PWM_HSD_OUT_13           , .pwm_instance = MODULE_5             , .pwm_channel = 0            },          
{           .pin_name = PWM_HSD_OUT_14           , .pwm_instance = MODULE_5             , .pwm_channel = 1            },          
{           .pin_name = PWM_HSD_OUT_15           , .pwm_instance = MODULE_5             , .pwm_channel = 2            },          
{           .pin_name = PWM_HSD_OUT_16           , .pwm_instance = MODULE_5             , .pwm_channel = 3            },          
{           .pin_name = PWM_MOTOR_1_NEG          , .pwm_instance = MODULE_7             , .pwm_channel = 1            },          
{           .pin_name = PWM_MOTOR_1_POS          , .pwm_instance = MODULE_7             , .pwm_channel = 0            },          
{           .pin_name = PWM_MOTOR_2_NEG          , .pwm_instance = MODULE_7             , .pwm_channel = 3            },          
{           .pin_name = PWM_MOTOR_2_POS          , .pwm_instance = MODULE_7             , .pwm_channel = 2            },          
{           .pin_name = PWM_SOLAR_LOAD           , .pwm_instance = MODULE_6             , .pwm_channel = 3            },          
{           .pin_name = PWM_MAX                  , .pwm_instance = MODULE_NONE          , .pwm_channel = -1           },          
{           .pin_name = FREQ_IN1                 , .pwm_instance = MODULE_1             , .pwm_channel = 1            },          
{           .pin_name = FREQ_IN2                 , .pwm_instance = MODULE_1             , .pwm_channel = 0            },          
{           .pin_name = FREQ_IN3                 , .pwm_instance = MODULE_1             , .pwm_channel = 7            },          
{           .pin_name = FREQ_IN4                 , .pwm_instance = MODULE_1             , .pwm_channel = 6            },          
{           .pin_name = FREQ_IN5                 , .pwm_instance = MODULE_2             , .pwm_channel = 1            },          
{           .pin_name = FREQ_IN6                 , .pwm_instance = MODULE_2             , .pwm_channel = 0            },          
{           .pin_name = FREQ_IN7                 , .pwm_instance = MODULE_2             , .pwm_channel = 6            },          
{           .pin_name = FREQ_KL15                , .pwm_instance = MODULE_1             , .pwm_channel = 5            },          
{           .pin_name = FREQ_MAX                 , .pwm_instance = MODULE_NONE          , .pwm_channel = -1           },          
};
